fix to select the target value columns
case: DataFrame is not allowed

message: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 1
----> 1 rf_model, pred_RF = dd_PPC.pipeline.apply_random_forest()

File <string>:4, in apply_random_forest()

File ~/Jupyter_python/dd_PPC/books/../codes/dd_PPC/model/_model.py:10, in fit_random_forest(x_train_std, y_train, show_fit_process, show_pred_plot)
      7 _verbose = 2 if show_fit_process else 0
      9 RF = RandomForestRegressor(verbose=_verbose)
---> 10 RF.fit(x_train_std, y_train)
     12 pred_RF = RF.predict(x_train_std)
     14 if show_pred_plot:

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/base.py:1365, in _fit_context.<locals>.decorator.<locals>.wrapper(estimator, *args, **kwargs)
   1358     estimator._validate_params()
   1360 with config_context(
   1361     skip_parameter_validation=(
   1362         prefer_skip_nested_validation or global_skip_validation
   1363     )
   1364 ):
-> 1365     return fit_method(estimator, *args, **kwargs)

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/ensemble/_forest.py:359, in BaseForest.fit(self, X, y, sample_weight)
    356 if issparse(y):
    357     raise ValueError("sparse multilabel-indicator for y is not supported.")
--> 359 X, y = validate_data(
    360     self,
    361     X,
    362     y,
    363     multi_output=True,
    364     accept_sparse="csc",
    365     dtype=DTYPE,
    366     ensure_all_finite=False,
    367 )
    368 # _compute_missing_values_in_feature_mask checks if X has missing values and
    369 # will raise an error if the underlying tree base estimator can't handle missing
    370 # values. Only the criterion is required to determine if the tree supports
    371 # missing values.
    372 estimator = type(self.estimator)(criterion=self.criterion)

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/utils/validation.py:2971, in validate_data(_estimator, X, y, reset, validate_separately, skip_check_array, **check_params)
   2969         y = check_array(y, input_name="y", **check_y_params)
   2970     else:
-> 2971         X, y = check_X_y(X, y, **check_params)
   2972     out = X, y
   2974 if not no_val_X and check_params.get("ensure_2d", True):

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/utils/validation.py:1368, in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_writeable, force_all_finite, ensure_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
   1362     raise ValueError(
   1363         f"{estimator_name} requires y to be passed, but the target y is None"
   1364     )
   1366 ensure_all_finite = _deprecate_force_all_finite(force_all_finite, ensure_all_finite)
-> 1368 X = check_array(
   1369     X,
   1370     accept_sparse=accept_sparse,
   1371     accept_large_sparse=accept_large_sparse,
   1372     dtype=dtype,
   1373     order=order,
   1374     copy=copy,
   1375     force_writeable=force_writeable,
   1376     ensure_all_finite=ensure_all_finite,
   1377     ensure_2d=ensure_2d,
   1378     allow_nd=allow_nd,
   1379     ensure_min_samples=ensure_min_samples,
   1380     ensure_min_features=ensure_min_features,
   1381     estimator=estimator,
   1382     input_name="X",
   1383 )
   1385 y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
   1387 check_consistent_length(X, y)

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/utils/validation.py:1053, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_writeable, force_all_finite, ensure_all_finite, ensure_non_negative, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
   1051         array = xp.astype(array, dtype, copy=False)
   1052     else:
-> 1053         array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
   1054 except ComplexWarning as complex_warning:
   1055     raise ValueError(
   1056         "Complex data not supported\n{}\n".format(array)
   1057     ) from complex_warning

File ~/opt/anaconda3/envs/dd_PPC/lib/python3.12/site-packages/sklearn/utils/_array_api.py:757, in _asarray_with_order(array, dtype, order, copy, xp, device)
    755     array = numpy.array(array, order=order, dtype=dtype)
    756 else:
--> 757     array = numpy.asarray(array, order=order, dtype=dtype)
    759 # At this point array is a NumPy ndarray. We convert it to an array
    760 # container that is consistent with the input's namespace.
    761 return xp.asarray(array)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.