fix AttributeError to use list of LGBMRegressor for metrics calculation
case: The model is changed to multi model list

message: AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 dd_PPC.pipeline.fit_and_test_lightgbm()

File ~/Jupyter_python/dd_PPC/books/../codes/dd_PPC/pipeline/_lightgbm.py:99, in fit_and_test_lightgbm(boxcox_lambda)
     95 _LBs, _pred_LBs, _sc, _ir = fit_data(train_x, train_cons_y, train_rate_y)
     97 _x_test, _y_test, _consumption, _pred_cons_y, _pred_rate_y = pred_data(test_x, test_cons_y, _sc, _LBs, _ir)
---> 99 show_metrics(_pred_cons_y, _y_test, _pred_rate_y, _consumption, _LBs, _x_test, test_rate_y)

File ~/Jupyter_python/dd_PPC/books/../codes/dd_PPC/pipeline/_lightgbm.py:85, in fit_and_test_lightgbm.<locals>.show_metrics(pred_cons_y, y_test, pred_rate_y, consumption, lb, x_test, test_rate_y_)
     83 print(f'RMSE: {np.sqrt(np.mean((pred_cons_y - y_test) ** 2))}')
     84 print(f'MAE: {np.mean(np.abs(pred_cons_y - y_test))}')
---> 85 print(f'R2: {lb.score(x_test, y_test)}')
     86 print(
     87     f'CompetitionScore: {calc.weighted_average_of_consumption_and_poverty_rate(consumption, pred_rate_y, test_rate_y_)}')

AttributeError: 'list' object has no attribute 'score'